name: GitHub Pages Deployment CI/CD

on:
  push:
    branches:
      - main
  pull_request:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
      - uses: actions/upload-artifact@v4
        with:
          name: docusaurus
          path: build

  deploy:

    concurrency:
      group: "pages"
      cancel-in-progress: false

    if: github.ref_type == 'branch' && github.ref_name == 'main'

    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docusaurus
          path: docusaurus
      - name: Configure Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docusaurus
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
